<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Rocking red ticket');

echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" lang="es">
    <head>
    <!--<meta name="description" content="Punto de financiación para emprendedores y ofertas de trabajo. ¡Vamos a poner fin a esta crisis!"/>
    <meta property="og:title" content="EL DESAFÍO ESCARLATA"/>
    <meta property="og:url" content="http://www.labutacaescarlata.com/proyecto/la-butaca-escarlata/"/>
    <meta property="og:image" content="http://www.labutacaescarlata.com/img/proyecto.jpg" />
    <meta property="og:description"
          content="¡Regístrate y obtén capital y grandes descuentos!"/>-->
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/global.css')->prependStylesheet($this->baseUrl().'/css/custom-theme/jquery-ui-1.8.13.custom.css'); ?>
        <?php //echo $this->headScript()->prependFile($this->baseUrl().'/js/jquery-1.5.1.min.js');?>
        <?php //echo $this->headScript()->prependFile($this->baseUrl().'/js/jquery-ui-1.8.13.custom.min.js');?>
        <?=$this->jQuery()->setLocalPath( STATIC_PATH.'/js/jquery-1.5.1.min.js');?>
        <?=$this->jQuery()->setUiLocalPath( STATIC_PATH.'/js/jquery-ui-1.8.13.custom.min.js');?>
        <?=$this->jQuery()->uiEnable();?>
        <?= $this->headScript()->prependFile($this->baseUrl().'/js/comun.js'); ?>
        <!--[if lt IE 8]> <link href="/css/ie.css" rel="stylesheet" type="text/css"> <![endif]-->

    </head>
    <body>
        <div id="body">
		<div id="header">
                        <div id="logo"></div>
			<div id="user">
                            <?
                                $auth = Zend_Auth::getInstance ();
                                if ($auth->hasIdentity()):?>
                                <div id="profile">
                                    <div>Hello, <a href="/usuario/perfil/<?=$auth->getIdentity()->username?>"><?=$auth->getIdentity()->username?></a></div>
                                    <div><a href="/usuario/logout">Logout</a></div>
                                    <input type="hidden" id="idUser" value="<?=$auth->getIdentity()->id_usuario?>"/>
                                    <input type="hidden" id="user_sponsor" value="<?=$auth->getIdentity()->cod_patrocinio?>"/>
                                </div>
                            <?else:?>
                                <form action="/usuario/login" method="post">
                                    <span>User:</span><input type="text" name="user"/>
                                    <span>Password:</span><input type="password" name="password"/>
                                    <input type="submit" value="Log in"/>
                                    <input type="button" class="fb" value=""/>
                                </form>
                                <div><a href="/usuario/forgot/">Forgot your password?</a></div>
                                <div><a href="/usuario/register/">Join now!</a></div>
                            <?endif;?>
			</div>
			<div id="social">
                            <?$config = Zend_Registry::get('config');?>
                            <a href="<?=$config->social->urlTuenti?>" target="_blank"><img src="/img/tu.png"/></a>
                            <a href="<?=$config->social->urlLinkedin?>" target="_blank"><img src="/img/in.png"/></a>
                            <a href="<?=$config->social->urlTwitter?>" target="_blank" ><img src="/img/tw.png"/></a>
                            <a href="<?=$config->social->urlFacebook?>" target="_blank"><img src="/img/fb_ico.png"/></a>
                            

                        </div>
			<div id="title">
				<span>Make things happen</span>
				<div></div>
			</div>

			<div id="menu">
				<ul>
					<li <?=($_SERVER['REQUEST_URI']=="/")?"class='active'":""?>><a href="/">Home</a></li>
					<li <?=(substr_count($_SERVER['REQUEST_URI'],"/proyecto")>0)?"class='active'":""?>><a href="/proyectos/">Events</a></li>
					<li <?=(substr_count($_SERVER['REQUEST_URI'],"/sobre")>0)?"class='active'":""?>><a href="/sobre/">About RRT</a></li>
					<li <?=(substr_count($_SERVER['REQUEST_URI'],"/funcion")>0)?"class='active'":""?>><a href="/funciona/">How does it works</a></li>
					<li <?=(substr_count($_SERVER['REQUEST_URI'],"/faq")>0)?"class='active'":""?>><a href="/faq/">FAQ</a></li>
					<li><a href="http://labutacaescarlata.blogspot.com/" target="_blank">Blog</a></li>
				</ul>
				<div class="cl"></div>
			</div>
			
                        <div class="cl"></div>
		</div>
                <div id="content">
                    <?php echo $this->layout()->content; ?>
                </div>
                <div id="footer">
                        <div id="pp_horizontal"></div>
                        <div class="social_widgets">
                            <div id="fbs">
                                <div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) {return;}
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#appId=43853116540&xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class="fb-like" data-href="http://labutacaescarlata.com" data-send="true" data-layout="standard" data-width="300" data-show-faces="true" data-colorscheme="light" data-font="arial"></div>
                            </div>
                            <div>
                                <a href="https://twitter.com/share" class="twitter-share-button" data-url="http://labutacaescarlata.com" data-count="horizontal" data-via="butacaescarlata">Tweet</a><script type="text/javascript" src="//platform.twitter.com/widgets.js"></script>
                            </div>
                        </div>
			<div class="panel">
				<div class="terminos">&nbsp;<!--<a href="/aviso/">Aviso legal</a>--></div>
				<div class="terminos">&nbsp;<!--<a href="/politica/">Política de privacidad</a>--></div>
				<div class="terminos"><a href="/condiciones/">Term of use</a></div>
				<div class="terminos"><a href="/contacto/">Contact</a></div>
                                <div id="moloko"><div></div> <a href="http://www.molokofactory.com" target="_blank"><img src="/img/molokologo.png"></img></a></div>
			</div>
                        
		</div>
        </div>
        <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-26062159-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
    </body>
</html>
