<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('La butaca escarlata');

echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/global.css')->prependStylesheet($this->baseUrl().'/css/custom-theme/jquery-ui-1.8.13.custom.css'); ?>
        <?php //echo $this->headScript()->prependFile($this->baseUrl().'/js/jquery-1.5.1.min.js');?>
        <?php //echo $this->headScript()->prependFile($this->baseUrl().'/js/jquery-ui-1.8.13.custom.min.js');?>
        <?=$this->jQuery()->setLocalPath( STATIC_PATH.'/js/jquery-1.5.1.min.js');?>
        <?=$this->jQuery()->setUiLocalPath( STATIC_PATH.'/js/jquery-ui-1.8.13.custom.min.js');?>
        <?=$this->jQuery()->uiEnable();?>
        <?= $this->headScript()->prependFile($this->baseUrl().'/js/comun.js'); ?>
    </head>
    <body>
        <div id="body">
		<div id="header">

			<div id="user">
                            <?
                                $auth = Zend_Auth::getInstance ();
                                if ($auth->hasIdentity()):?>
                                <div id="profile">
                                    <div>Hola, <a href="/usuario/perfil/<?=$auth->getIdentity()->username?>"><?=$auth->getIdentity()->username?></a></div>
                                    <div><a href="/usuario/logout">Desconectar</a></div>
                                </div>
                            <?else:?>
                                <form action="/usuario/login" method="post">
                                    <span>Usuario:</span><input type="text" name="user"/>
                                    <span>Contraseña:</span><input type="password" name="password"/>
                                    <input type="submit" value="Acceder"/>
                                    <input type="button" class="fb" value=""/>
                                </form>
                                <div><a href="/usuario/forgot/">¿Ha olvidado sus datos?</a></div>
                                <div><a href="/usuario/register/">Registrarse</a></div>
                            <?endif;?>
			</div>
			<div id="social"></div>
			<div id="title">
				<span>Una buena idea no tiene precio, para todo lo demás...</span>
				<div></div>
			</div>

			<div id="menu">
				<ul>
					<li <?=($_SERVER['REQUEST_URI']=="/")?"class='active'":""?>><a href="/">Inicio</a></li>
					<li <?=(substr_count($_SERVER['REQUEST_URI'],"/proyecto")>0)?"class='active'":""?>><a href="/proyecto/la-butaca-escarlata">Proyectos</a></li>
					<li <?=(substr_count($_SERVER['REQUEST_URI'],"/sobre")>0)?"class='active'":""?>><a href="/sobre/">Sobre LBE</a></li>
					<li <?=(substr_count($_SERVER['REQUEST_URI'],"/funcion")>0)?"class='active'":""?>><a href="/funciona/">Cómo funciona</a></li>
					<li <?=(substr_count($_SERVER['REQUEST_URI'],"/faq")>0)?"class='active'":""?>><a href="/faq/">FAQ</a></li>
					<li><a href="http://labutacaescarlata.blogspot.com/">Blog & Foro</a></li>
				</ul>
				<div class="cl"></div>
			</div>
			<div id="logo"></div>
		</div>
                <div id="content">
                    <?php echo $this->layout()->content; ?>
                </div>
                <div id="footer">
			<div class="panel">
				<div class="terminos"><a href="/aviso/">Aviso legal</a></div>
				<div class="terminos"><a href="/politica/">Política de privacidad</a></div>
				<div class="terminos"><a href="/condiciones/">Condiciones de uso</a></div>
				<div class="terminos"><a href="/contacto/">Contacto</a></div>
			</div>
		</div>
        </div>
    </body>
</html>