<div id="panel-home">
    <div id="destacado">
        <div class="top"></div>
        <div class="destacado-content">
            <div id="noticias">
                <div class="scroll-pane ui-widget ui-widget-header ui-corner-all">
	            <div id="scroll-bar-wrap" class="scroll-bar-wrap ui-widget-content ui-corner-bottom">
                            <div class="scroll-bar"></div>
                    </div>
                    <div class="scroll-content">
                        <ul>
                            <?foreach($this->news as $new):?>
                            <li>
                                <div class="noticias-fecha"><?=$new->fecha?></div>
                                <?=$new->texto?>
                            </li>
                            <?endforeach;?>
                        </ul>
                    </div>
                   
                </div>
            </div>
            <div id="ficha">
                <div id="ficha-iconos"></div>
                <h1>Proyecto: <?=$this->project->titulo?></h1>
                <div id="ficha-imagen"><img src="<?=$this->image?>"></div>
                <div id="ficha-info">
                    <div class="number"><span id="porcentaje"><?=round($this->porcentaje,0)?></span> %</div>
                    <div class="text">recaudado</div>
                    <div id="progressbar"></div>
                    <div class="text"><?=round($this->recaudado,0)?> de <?=round($this->project->importe_solicitado,0)?> &euro;</div>
                    <div class="number margin"><?=$this->numApoyos?></div>
                    <div class="text">apoyos</div>
                    <div class="number margin"><?=$this->days?></div>
                    <div class="text">días</div>
                </div>
                
                <div id="ficha-bottom">
                    <h2>COMUNIDAD ONLINE DE "CROWFUNDING & CROWSORCING" EMPRESARIAL</h2>
                    <span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur at nulla leo. Phasellus a elit a massa egestas tristique eu id justo. Praesent non arcu neque. Suspendisse aliquet auctor ante, at posuere neque cursus quis. Praesent vitae</span>
                </div>
            </div>
        </div>
        <div class="bottom"></div>
    </div>
    <div id="bottom-home">
    </div>
</div>