<div id="panel-form" class="create-project">
     <?if ($this->msg!=""):?>
        <h2>Process succeeded</h2>
        <div class="msg"><?=$this->msg?></div>
    <?else:?>
        <h2>Creat your event in the Rocket Red Ticket</h2>
         <?php if (isset ( $this->error )) :?>
            <ul class="errors">
                 <?=$this->error ;?>
            </ul>
         <?php endif;?>
        <fieldset>
            <form action="<?=$this->escape ( $this->form->getAction () )?>" method="<?=$this->escape ( $this->form->getMethod () )?>" enctype="multipart/form-data">
                <?

                echo $this->form->titulo;
                echo $this->form->ciudad;
                echo $this->form->fecha_evento;
                $option="<option></option>";
                foreach($this->category as $cat){
                    $option.="<option value='".$cat['id_categoria']."'>".$cat['categoria']."</option>";
                }
                echo '<div id="categoria-label"><label class="required" for="id_categoria">Category:</label></div>';
                echo '<span class="data"><select name="id_categoria" id="id_categoria">'.$option."</select></span>";
                echo $this->form->breve_descripcion;
                echo $this->form->descripcion;
                echo $this->form->video_embed;?>

                <div id="fecha-imagen">
                    <label class="required" for="imagen">Image:</label>
                </div>
                <span class="data">
                    <input type="file" name="imagen"/>
                </span>
                <?echo $this->form->fecha;
                echo $this->form->importe;?>
                <div class="reward">
                    <h2>Rewards</h2>
                    <div id="reward-item" class="reward-item">
                        <?echo  str_replace("recompensa","recompensa[]", $this->form->recompensa);
                            echo str_replace("minimo","minimo[]", $this->form->minimo);
                            echo str_replace("\"subasta","\"subasta[]", $this->form->subasta);
                            ?>
                        <div>
                            <span class="data">
                                Auctioned?
                                <input class="check_subasta" type="checkbox" value="" name="subasta_1">
                            </span>
                            <span class="data">
                                Ticket not included
                                <input class="check_no_entrada" type="checkbox" value="" name="no_entrada_1">
                            </span>
                        </div>
                    </div>
                </div>
                <input type="button" id="btn-reward" class="btn-red" value="More"/>
                <input type="button" id="btn-reward-delete" class="btn-red" value="Less"/>
                <div class="contest">
                    <h2>Contest</h2>
                <?echo $this->form->titulo_concurso;
                echo $this->form->descripcion_concurso;?>
                </div>
                
                
                <div id="collaborator" class="collaborator">
                    <h2>Collaborators</h2>
                    <div id="collaborator-item" class="collaborator-item">
                        <?echo  str_replace("colaborador","colaborador[]", $this->form->colaborador);
                            echo str_replace("contacto","contacto[]", $this->form->contacto);
                            echo str_replace("\"descripcion_colaborador","\"descripcion_colaborador[]", $this->form->descripcion_colaborador);
                            ?>
                    </div>
                </div>
                <input type="button" id="btn-collaborator" class="btn-red" value="More"/>
                <input type="button" id="btn-collaborator-delete" class="btn-red" value="Less"/>
                
                <?echo $this->form->submit; ?>
            </form>
        </fieldset>
    <?endif;?>
</div>