<div id="panel-project">
    
    <div id="tabs">
	<ul>
		<li><a href="#tabs-1">Home</a></li>
		<li><a href="#tabs-2">Colaboradores</a></li>
		<li><a href="#tabs-3">Concursos</a></li>
	</ul>
	<div id="tabs-1">
            <div id="ficha">
                <div id="ficha-iconos"></div>
                <input type="hidden" id="link" value="<?=$this->project->link_rewrite?>"/>
                <h1><span>Proyecto: </span><?=$this->project->titulo?></h1>
                <div id="ficha-imagen"><img src="<?=$this->image?>"></div>
                <div id="ficha-info">
                    <div class="number"><span id="porcentaje"><?=round($this->porcentaje,0)?></span> %</div>
                    <div class="text">recaudado</div>
                    <div id="progressbar"></div>
                    <div class="text"><?=round($this->recaudado,0)?> de <?=round($this->project->importe_solicitado,0)?> &euro;</div>
                    <div class="number margin"><?=$this->numApoyos?></div>
                    <div class="text">apoyos</div>
                    <div class="number margin"><?=$this->days?></div>
                    <div class="text">días</div>
                </div>

                <div id="ficha-bottom">
                    <div id="project-social"></div>
                    <h2>Descripci&oacute;n del Proyecto</h2>
                    <span><?=$this->project->descripcion?></span>
                </div>
            </div>
	</div>
	<div id="tabs-2">
            <div id="colaboradores">
                <div class="colaborador">
                    <h2>colaborador requerido</h2>
                    <p class="contacto">Envíar mail a contacto@contacto.es</p>
                    <p>Descripción del colaborador requerido,  Mauris eleifend est et turpis. Duis id erat. Suspendisse potenti. Aliquam vulputate, pede vel vehicula accumsan, mi neque rutrum erat, eu congue orci lorem eget lorem. Vestibulum non ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce sodales. Quisque eu urna vel enim commodo pellentesque. Praesent eu risus hendrerit ligula tempus pretium. Curabitur lorem enim, pretium nec, feugiat nec, luctus a, lacus.</p>
                </div>
                <div class="colaborador">
                    <h2>colaborador requerido</h2>
                    <p class="contacto">Envíar mail a contacto@contacto.es</p>
                    <p>Descripción del colaborador requerido,  Mauris eleifend est et turpis. Duis id erat. Suspendisse potenti. Aliquam vulputate, pede vel vehicula accumsan, mi neque rutrum erat, eu congue orci lorem eget lorem. Vestibulum non ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce sodales. Quisque eu urna vel enim commodo pellentesque. Praesent eu risus hendrerit ligula tempus pretium. Curabitur lorem enim, pretium nec, feugiat nec, luctus a, lacus.</p>
                </div>
            </div>
	</div>
	<div id="tabs-3">
		<p>Mauris eleifend est et turpis. Duis id erat. Suspendisse potenti. Aliquam vulputate, pede vel vehicula accumsan, mi neque rutrum erat, eu congue orci lorem eget lorem. Vestibulum non ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce sodales. Quisque eu urna vel enim commodo pellentesque. Praesent eu risus hendrerit ligula tempus pretium. Curabitur lorem enim, pretium nec, feugiat nec, luctus a, lacus.</p>
		<p>Duis cursus. Maecenas ligula eros, blandit nec, pharetra at, semper at, magna. Nullam ac lacus. Nulla facilisi. Praesent viverra justo vitae neque. Praesent blandit adipiscing velit. Suspendisse potenti. Donec mattis, pede vel pharetra blandit, magna ligula faucibus eros, id euismod lacus dolor eget odio. Nam scelerisque. Donec non libero sed nulla mattis commodo. Ut sagittis. Donec nisi lectus, feugiat porttitor, tempor ac, tempor vitae, pede. Aenean vehicula velit eu tellus interdum rutrum. Maecenas commodo. Pellentesque nec elit. Fusce in lacus. Vivamus a libero vitae lectus hendrerit hendrerit.</p>
	</div>
    </div>
    <div id="recompensas">
        <span>Recompensas por apoyar el proyecto</span>
        <ul class="scroll-content-item ui-widget-header">
            <?foreach($this->rewards as $reward):?>
            <li>
                <div class="recompensa-valor"><?=$reward->apoyo_minimo?>&euro;</div>
                <div class="recompensa-desc"><?=$reward->recompensa?></div>
                <div id="<?=$reward->id_recompensa?>" class="btn-red">Apoyar</div>
            </li>
            <?endforeach;?>
            
        </ul>
    </div>
    <div class="cl"></div>
</div>