<div id="panel-funciona">
    <div id="funciona">
        <div id="enlaces">
            <div><a href="#que">Que es</a></div>
            <div><a href="#publicar">Publicar tu proyecto</a></div>
            <div><a href="#patrocinar">Patrocinar/invertir</a></div>
            <div><a href="#colaborar">Colaborar</a></div>
            <div><a href="#sistema">Sistema de pagos</a></div>
        </div>
    </div>
</div>
<div id="texto-funciona">
    <h3><a name="que">Que es</a></h3>
    <div class="txt"><?=$this->text[0]?></div>
    <h3 ><a name="publicar">Publicar tu proyecto</a></h3>
    <div class="txt"><?=$this->text[1]?></div>
    <h3><a name="patrocinar">Patrocinar/invertir</a></h3>
    <div class="txt"><?=$this->text[2]?></div>
    <h3><a name="colaborar">Colaborar</a></h3>
    <div class="txt"><?=$this->text[3]?></div>
    <h3><a name="sistema">Sistema de pagos</a></h3>
    <div class="txt"><?=$this->text[4]?></div>
</div>