<div id="panel-funciona">
    <div id="funciona">
        <div id="enlaces">
            <!--<div><a href="#que">Que es</a></div>-->
            <div><a href="#publicar">Create your event</a></div>
            <div><a href="#patrocinar">Support/attend an event</a></div>
            <div><a href="#colaborar">Collaborate</a></div>
            <div><a href="#sistema">Payment system</a></div>
        </div>
    </div>
</div>
<div id="texto-funciona">
    <!--<h3><a name="que">Que es</a></h3>
    <div class="txt"><?=$this->text[0]?></div>-->
    <h3 ><a name="publicar">Create your event</a></h3>
    <div class="txt"><?=$this->text[1]?></div>
    <h3><a name="patrocinar">Support/attend an event</a></h3>
    <div class="txt"><?=$this->text[2]?></div>
    <h3><a name="colaborar">Collaborate</a></h3>
    <div class="txt"><?=$this->text[3]?></div>
    <h3><a name="sistema">Payment system</a></h3>
    <div class="txt"><?=$this->text[4]?></div>
</div>