<div id="history">
    <h2>HISTORIA</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur nibh sem, sollicitudin eu mollis id, tincidunt ornare sem. In hac habitasse platea dictumst. Aliquam accumsan porta sodales. Ut adipiscing accumsan arcu, non pellentesque massa adipiscing ac. Aenean eu dui nisl, sit amet luctus augue. Vestibulum tincidunt interdum orci ut vehicula. Integer quis ligula id ipsum aliquet tincidunt eget vitae quam.</p>
    <div id="pruebame"></div>
</div>
