<?
function paintHomeMessage(){?>
<div class="cl"></div>
<div id="home-message"></div>

<?}
?>

<div id="panel-home">
    <div id="category-list">
        <span>Categories</span>
        <div class="mnu-cat"><a class="<?=(0==$this->idCategory?"active":"")?>" href="/events/<?=$this->page?>">All</a></div>
        <?foreach ($this->categories as $category):?>
            <div class="mnu-cat"><a class="<?=($category['id_categoria']==$this->idCategory?"active":"")?>" href="/events/<?=$this->page?>/<?=$category['id_categoria']?>"><?=$category['categoria']?></a></div>
        <?endforeach;?>
    </div>
    <div id="projects-home">
        <?$i=0;
            foreach ($this->projects as $project):
              $i++;
              if($i==4)
                  paintHomeMessage()
                    ?>
            <div class="item">
                <!--<div class="iconos"></div>-->
                <div class="locate">
                    <div><?=$project['ciudad']?></div>
                    <div><?=$project['fecha']?></div>
                </div>
                <div class="title"><span><a href="/event/<?=$project['link_rewrite']?>"><?=$project['titulo']?></a></span></div>
                <div class="project-image">
                    <img  width="123" src="<?="/admin/".str_replace("/".$project['id_proyecto']."/", "/".$project['id_proyecto']."/160x/thumb_", $project['imagen']);?>">
                </div>
                <div class="project-info">
                        <div class="number"><span id="porcentaje_<?=$i?>"><?=round($project['porcentaje'],0)?></span> %</div>
                        <div class="text">raised</div>
                        <div id="progressbar_<?=$i?>"></div>
                        <div class="number"><?=round($project['recaudado'],0)?> de <?=round($project['importe_solicitado'],0)?> &euro;</div>
                        <div class="number margin"><?=$project['numApoyos']?> <span class="text">attendees</span></div>
                        <div class="number margin"><?=$project['days']?> <span class="text">days</span></div>

                </div>
                <div class="project-bottom">
                    <?=$project['breve_descripcion']?>
                </div>

            </div>
        <?endforeach;
          if($i<4)
                  paintHomeMessage()?>
        <div class="cl"></div>
    </div>
</div>