<div id="panel-home">
    <div id="destacado">
        <div class="top"></div>
        <div class="destacado-content">
            <div id="noticias">Noticias</div>
            <div id="ficha">
                <div id="ficha-iconos"></div>
                <h1>Proyecto: La Butaca Escarlata</h1>
                <div id="ficha-imagen"><img src="/img/proyecto.jpg"></div>
                <div id="ficha-info">
                    <div class="number">78 %</div>
                    <div class="text">recaudad</div>
                    <div id="progressbar"></div>
                    <div class="text">3568 de 4000 &euro;</div>
                    <div class="number margin">35</div>
                    <div class="text">apoyos</div>
                    <div class="number margin">40</div>
                    <div class="text">días</div>
                </div>
                
                <div id="ficha-bottom">
                    <h2>COMUNIDAD ONLINE DE "CROWFUNDING & CROWSORCING" EMPRESARIAL</h2>
                    <span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur at nulla leo. Phasellus a elit a massa egestas tristique eu id justo. Praesent non arcu neque. Suspendisse aliquet auctor ante, at posuere neque cursus quis. Praesent vitae</span>
                </div>
            </div>
        </div>
        <div class="bottom"></div>
    </div>
    <div id="bottom-home">
    </div>
</div>