<?php
if ($this->pageCount): ?>
<div class="paginationControl">
<!-- Anterior page link -->
<?php if (isset($this->previous)): ?>
  <a href="<?="/proyectos/".$this->previous; ?>">< Previous</a> |
<?php else: ?>
  <span class="disabled">< Previous</span> |
<?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <a href="<?php echo "/proyectos/".$page; ?>"><?php echo $page; ?></a> |
  <?php else: ?>
    <b><?php echo $page; ?></b> |
  <?php endif; ?>
<?php endforeach; ?>

<!-- Siguiente page link -->
<?php if (isset($this->next)): ?>
  <a href="<?php echo "/proyectos/".$this->next; ?>">Next ></a>
<?php else: ?>
  <span class="disabled">Next ></span>
<?php endif; ?>
</div>
<?php endif; ?>