<?$helper=new View_Helper_Image();?>
<div id="panel-profile">
    
    <div id="acciones">
        <a href="#" id="image">Cambiar imagen de perfil</a>
        <a href="#" id="new-project">Crear proyecto</a>
        <a href="#" id="baja">Darse de baja</a>
    </div>
    <div id="datos">
        <img src="<?=$helper->image($this->user->id_usuario, $this->user->imagen)?>">
        <h2><?=$this->user->username?></h2>
    </div>
    <div class="cl"></div>
    <div class="profile-box">
        <h3>Proyectos que apoyas</h3>
        <ul>
            <li><a href="#">La butaca escarlata</a></li>
        </ul>
    </div>
    <div class="profile-box">
        <h3>Tus propuestas</h3>
        <ul>
            <li><a href="#">La butaca escarlata</a></li>
        </ul>
    </div>
    <div class="profile-box">
        <h3>Proyectos que has comentado</h3>
        <ul>
            <li><a href="#">La butaca escarlata</a></li>
        </ul>
    </div>
    <div class="profile-box">
        <h3>Concursos que has comentado</h3>
        <ul>
            <li><a href="#">La butaca escarlata</a></li>
        </ul>
    </div>
    <div class="cl"></div>
</div>
<div id="dialog-form" title="Darse de baja">
    <div>
        <p>&iquest;Desea darse de baja de La Butaca escarlata?</p>
    </div>
</div>
<div id="dialog-form-image" title="Cambiar imagen">
    <div>
        <form id="frm-image" method="post" enctype="multipart/form-data">
            Selecciona tu nueva imagen de perfil<input type="file" name="imagen"/>
        </form>
    </div>
</div>