<?$helper=new View_Helper_Image();?>
<div id="panel-profile">
    <input type="hidden" id="preapproval"/>
    <div id="acciones">
        <a href="#" id="image">Cambiar imagen de perfil</a>
        <a href="#" id="new-project">Crear proyecto</a>
        <a href="#" id="baja">Darse de baja</a>
    </div>
    <div id="datos">
        <img src="<?=$helper->image($this->user->id_usuario, $this->user->imagen)?>">
        <h2><?=$this->user->username?></h2>
    </div>
    <div class="cl"></div>
    <div class="profile-box">
        <h3>Proyectos que apoyas</h3>
        <ul>
            <?
            $first=true;
            $latsProject="";
            foreach($this->supports as $support):
                    if($lastProject!=$support['titulo']){
                        if(!$first)
                            echo '</ul></li>';
                        $first=false;?>
                       <li><a href="/proyecto/<?=$support['link_rewrite']?>"><?=$support['titulo']?></a>
                    <ul>

                <?}
                    $lastProject=$support['titulo'];

                    ?>


                        <li><?=$support['apoyo']?> &euro; por <i><?=$support['recompensa']?></i>
                            <?if($support['subasta']!="S"):?>
                                <div class="action-box"><a class="cancel-preaproval" id="<?=$support['preapproved_key']?>">Cancelar apoyo</a></div>
                            <?endif;?>
                        </li>
                    
           <?endforeach;?>
        </ul>
    </div>
    <div class="profile-box">
        <h3>Tus propuestas</h3>
        <ul>
            <?foreach($this->proposals as $item):?>
                <li>has realizado <?=$item['c']?> propuesta<?=($item['c']>1?"s":"")?> al proyecto <a href="/proyecto/<?=$item['link_rewrite']?>"><?=$item['titulo']?></a></li>
            <?endforeach;?>
        </ul>
    </div>
    <div class="profile-box">
        <h3>Proyectos que has comentado</h3>
        <ul>
            <?foreach($this->comments as $item):?>
                <li><a href="/proyecto/<?=$item['link_rewrite']?>"><?=$item['titulo']?></a> (<?=$item['comentarios']?> comentario<?=($item['comentarios']>1?"s":"")?>)</li>
            <?endforeach;?>
        </ul>
    </div>
    <div class="profile-box">
        <h3>Propuestas de concursos que has comentado</h3>
        <ul>
              <?
            $first=true;
            $lastProject="";
            foreach($this->proposalsComments as $item):
                    if($lastProject!=$item['titulo']){
                        if(!$first)
                            echo '</ul></li>';
                        $first=false;?>
                       <li>Has comentado el concurso del proyecto <a href="/proyecto/<?=$item['link_rewrite']?>"><?=$item['titulo']?></a>
                    <ul>

                <?}
                    $lastProject=$item['titulo'];

                    ?>


                        <li>La propuesta de <i><?=$item['username']?></i></li>

           <?endforeach;?>
        </ul>
    </div>
    <div class="cl"></div>
</div>
<div id="dialog-form" title="Darse de baja">
    <div>
        <p>&iquest;Desea darse de baja de La Butaca escarlata?</p>
    </div>
</div>
<div id="dialog-form-cancel" title="Dejar de apoyar el proyecto">
    <div>
        <p>&iquest;Desea cancelar completame este apoyo?</p>
    </div>
</div>
<div id="dialog-form-image" title="Cambiar imagen">
    <div>
        <form id="frm-image" method="post" enctype="multipart/form-data">
            Selecciona tu nueva imagen de perfil<input type="file" name="imagen"/>
        </form>
    </div>
</div>