<div id="panel-form">
    <h2>New user</h2>
    <?if ($this->procesado):?>
        <div class="msg">We have have just send an email with the instructions to fulfill your registration. Check your SPAM folder in case you don’t receive it! ;)</div>
    <?else:?>
        <?php
        if (isset ( $this->error )) :
            ?>
        <ul class="errors">
                <?=$this->error ;?>
        </ul>
        <?php endif;?>
        <fieldset>
            <p>If you are already registered, &nbsp;<a href="/usuario/login" title="user login">click here</a></p>
            <form action="<?=$this->escape ( $this->form->getAction () )?>" method="<?=$this->escape ( $this->form->getMethod () )?>">
                <?
                echo $this->form->email;
                echo $this->form->username;
                echo $this->form->password1;
                echo $this->form->password2;
                echo $this->form->patrocinador;?>
                <span id="agree">
                <?=$this->form->agree;?> I have read and accepted the <a href="/condiciones/">Terms of use</a>
                </span>
                <? echo $this->form->submit; ?>
                <? echo $this->form->fb; ?>


            </form>
        </fieldset>
    <?endif;?>
</div>

