<div id="panel-form">
    <h2>Nuevo Usuario</h2>
    <?if ($this->procesado):?>
        <div class="msg">Hemos enviado a tu correo electr&oacute;nico las instrucciones para que puedas completar tu registro. Comprueba la bandeja de SPAM, por si acaso ;)</div>
    <?else:?>
        <?php
        if (isset ( $this->error )) :
            ?>
        <ul class="errors">
                <?=$this->error ;?>
        </ul>
        <?php endif;?>
        <fieldset>
            <p>Si ya est&aacute;s registrado, &nbsp;<a href="/usuario/login" title="user login">Entra aqu&iacute;</a></p>
            <form action="<?=$this->escape ( $this->form->getAction () )?>" method="<?=$this->escape ( $this->form->getMethod () )?>">
                <?
                echo $this->form->email;
                echo $this->form->username;
                echo $this->form->password1;
                echo $this->form->password2;?>
                <span id="agree">
                <?=$this->form->agree;?> He leido y acepto los <a href="/condiciones/">Condiciones de uso</a> y la <a href="/politica/">Pol&iacute;tica de privacidad</a>
                </span>
                <? echo $this->form->submit; ?>
                <? echo $this->form->fb; ?>


            </form>
        </fieldset>
    <?endif;?>
</div>

