<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('La butaca escarlata');

echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/global.css'); ?>
        <?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/custom-theme/jquery-ui-1.8.13.custom.css'); ?>
        <?php //echo $this->headScript()->prependFile($this->baseUrl().'/js/jquery-1.5.1.min.js');?>
        <?php //echo $this->headScript()->prependFile($this->baseUrl().'/js/jquery-ui-1.8.13.custom.min.js');?>
        <?=$this->jQuery()->setLocalPath( STATIC_PATH.'/js/jquery-1.5.1.min.js');?>
        <?=$this->jQuery()->setUiLocalPath( STATIC_PATH.'/js/jquery-ui-1.8.13.custom.min.js');?>
        <?=$this->jQuery()->uiEnable();?>
        <?= $this->headScript(); ?>
    </head>
    <body>
        <div id="body">
		<div id="header">

			<div id="user">
				<span>Usuario:</span><input type="text"/>
				<span>Contraseña:</span><input type="password"/>
				<input type="button" value="Acceder"/>
				<div><a href="#">¿Ha olvidado sus datos?</a></div>
				<div><a href="#">Registrarse</a></div>
			</div>
			<div id="social"></div>
			<div id="title">
				<span>Una buena idea no tiene precio, para todo lo demás...</span>
				<div></div>
			</div>

			<div id="menu">
				<ul>
					<li><a href="#">Inicio</a></li>
					<li><a href="#">Proyectos</a></li>
					<li><a href="#">Sobre LBE</a></li>
					<li><a href="#">Cómo funciona</a></li>
					<li><a href="#">FAQ</a></li>
					<li><a href="#">Blog & Foro</a></li>
				</ul>
				<div class="cl"></div>
			</div>
			<div id="logo"></div>
		</div>
                <div id="content">
                    <?php echo $this->layout()->content; ?>
                </div>
                <div id="footer">
			<div class="panel">
				<div class="terminos"><a href="#">Aviso legal</a></div>
				<div class="terminos"><a href="#">Política de privacidad</a></div>
				<div class="terminos"><a href="#">Condiciones de uso</a></div>
				<div class="terminos"><a href="#">Contacto</a></div>
			</div>
		</div>
        </div>
    </body>
</html>