<div id="panel-form">
    <h2>Contact</h2>
    <?if ($this->procesado):?>
        <div class="msg">Please contact us, we have received your message.</div>
    <?else:?>
        <?php
        if (isset ( $this->error )) :
            ?>
        <ul class="errors">
                <?=$this->error ;?>
        </ul>
        <?php endif;?>
        <fieldset>
            <form action="<?=$this->escape ( $this->form->getAction () )?>" method="<?=$this->escape ( $this->form->getMethod () )?>">
            <?
                    echo $this->form->email;
                    echo $this->form->message;?>
                    <span id="agree">
                    <?=$this->form->agree?> i have read and accepted the <a href="/condiciones/">Terms of use</a>
                    </span>
                    <? echo $this->form->submit; ?>
            </form>
        </fieldset>
    <?endif;?>
</div>

