<div id="panel-funciona">
    <div id="funciona">
        <div id="enlaces">
            <div><a href="#que">Que es</a></div>
            <div><a href="#publicar">Publicar tu proyecto</a></div>
            <div><a href="#patrocinar">Patrocinar/invertir</a></div>
            <div><a href="#colaborar">Colaborar</a></div>
            <div><a href="#sistema">Sistema de pagos</a></div>
        </div>
    </div>
</div>
<div id="texto-funciona">
    <h3><a name="que">Que es</a></h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum faucibus commodo porttitor. In sollicitudin rutrum neque non lacinia. Quisque a enim faucibus lorem convallis sollicitudin. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse cursus felis et arcu tempor aliquet. Vivamus lobortis pretium tortor, eu pretium magna hendrerit nec</p>
    <h3><a name="publicar">Publicar tu proyecto</a></h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum faucibus commodo porttitor. In sollicitudin rutrum neque non lacinia. Quisque a enim faucibus lorem convallis sollicitudin. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse cursus felis et arcu tempor aliquet. Vivamus lobortis pretium tortor, eu pretium magna hendrerit nec</p>
    <h3><a name="patrocinar">Patrocinar/invertir</a></h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum faucibus commodo porttitor. In sollicitudin rutrum neque non lacinia. Quisque a enim faucibus lorem convallis sollicitudin. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse cursus felis et arcu tempor aliquet. Vivamus lobortis pretium tortor, eu pretium magna hendrerit nec</p>
    <h3><a name="colaborar">Colaborar</a></h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum faucibus commodo porttitor. In sollicitudin rutrum neque non lacinia. Quisque a enim faucibus lorem convallis sollicitudin. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse cursus felis et arcu tempor aliquet. Vivamus lobortis pretium tortor, eu pretium magna hendrerit nec</p>
    <h3><a name="sistema">Sistema de pagos</a></h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum faucibus commodo porttitor. In sollicitudin rutrum neque non lacinia. Quisque a enim faucibus lorem convallis sollicitudin. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse cursus felis et arcu tempor aliquet. Vivamus lobortis pretium tortor, eu pretium magna hendrerit nec</p>
</div>