<div class="static">
        <h2>POLITICA</h2>
        <h3>titulo</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent lobortis faucibus arcu, eu mattis dui tincidunt id. Praesent nisi augue, placerat dictum blandit sit amet, porttitor in tortor. Sed sed tempus nibh. Aliquam id sem eget enim tristique sollicitudin vel quis magna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Integer eget magna et mauris ultrices laoreet vel non sapien.</p>
        <h3>titulo</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent lobortis faucibus arcu, eu mattis dui tincidunt id. Praesent nisi augue, placerat dictum blandit sit amet, porttitor in tortor. Sed sed tempus nibh. Aliquam id sem eget enim tristique sollicitudin vel quis magna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Integer eget magna et mauris ultrices laoreet vel non sapien.</p>
        <h3>titulo</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent lobortis faucibus arcu, eu mattis dui tincidunt id. Praesent nisi augue, placerat dictum blandit sit amet, porttitor in tortor. Sed sed tempus nibh. Aliquam id sem eget enim tristique sollicitudin vel quis magna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Integer eget magna et mauris ultrices laoreet vel non sapien.</p>
        <h3>titulo</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent lobortis faucibus arcu, eu mattis dui tincidunt id. Praesent nisi augue, placerat dictum blandit sit amet, porttitor in tortor. Sed sed tempus nibh. Aliquam id sem eget enim tristique sollicitudin vel quis magna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Integer eget magna et mauris ultrices laoreet vel non sapien.</p>
        <h3>titulo</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent lobortis faucibus arcu, eu mattis dui tincidunt id. Praesent nisi augue, placerat dictum blandit sit amet, porttitor in tortor. Sed sed tempus nibh. Aliquam id sem eget enim tristique sollicitudin vel quis magna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Integer eget magna et mauris ultrices laoreet vel non sapien.</p>
</div>