<div id="panel-form">
    <h2>Reset connection data</h2>
    <?if ($this->procesado):?>
        <div class="msg">We have have just send an email with the instructions to fulfill your registration. Check your SPAM folder in case you don’t receive it! ;)</div>
    <?else:?>
         <?if (isset ( $this->error )):?>
        <ul class="errors">
                <?=$this->error ;?>
        </ul>
        <?endif;?>
        <?= $this->form ?>
    <?endif;?>
</div>