<div id="panel-form" class="create-project">
     <?if ($this->msg!=""):?>
        <h2>Proceso finalizado correctamente</h2>
        <div class="msg"><?=$this->msg?></div>
    <?else:?>
        <h2>Introduce tu proyecto en La Butaca Escarlata </h2>
         <?php if (isset ( $this->error )) :?>
            <ul class="errors">
                 <?=$this->error ;?>
            </ul>
         <?php endif;?>
        <fieldset>
            <form action="<?=$this->escape ( $this->form->getAction () )?>" method="<?=$this->escape ( $this->form->getMethod () )?>" enctype="multipart/form-data">
                <?
                echo $this->form->titulo;
                echo $this->form->categoria;
                echo $this->form->breve_descripcion;
                echo $this->form->descripcion;
                echo $this->form->video_embed;?>

                <div id="fecha-imagen">
                    <label class="required" for="imagen">Imagen del proyecto:</label>
                </div>
                <span class="data">
                    <input type="file" name="imagen"/>
                </span>
                <?echo $this->form->fecha;
                echo $this->form->importe;?>
                <div class="reward">
                    <div id="reward-item" class="reward-item">
                        <span>Recompensa nº <b>1</b></span>
                        <?echo  str_replace("recompensa","recompensa[]", $this->form->recompensa);
                            echo str_replace("minimo","minimo[]", $this->form->minimo);
                            echo str_replace("\"subasta","\"subasta[]", $this->form->subasta);
                            ?>
                        <div>
                            <span class="data">
                                ¿Se subasta?
                                <input class="check_subasta" type="checkbox" value="" name="subasta_1">
                            </span>
                        </div>
                    </div>
                </div>
                <input type="button" id="btn-reward" class="btn-red" value="Más"/>
                <input type="button" id="btn-reward-delete" class="btn-red" value="Menos"/>
                <?echo $this->form->submit; ?>
            </form>
        </fieldset>
    <?endif;?>
</div>