<?$helper=new View_Helper_Image();
$helperDate=new View_Helper_Date();?>
<?if (isset($this->proposalUpload)):?>
    <div id="panel-form">
        <h2><?=($this->proposalUpload)?"Su propuesta se ha registrador correctamente.":"Ha ocurrido un error al registrar su propuesta"?></h2>
        <div><a id="back-project">Volver al proyecto</a></div>
    </div>
<?endif;?>

<div id="panel-project" <?=isset($this->proposalUpload)?"style='display:none'":""?>>
    
    <div id="tabs">
	<ul>
		<li><a href="#tabs-1">Home</a></li>
		<li><a href="#tabs-2">Colaboradores</a></li>
		<li><a href="#tabs-3">Concursos</a></li>
	</ul>
	<div id="tabs-1">
            <div id="ficha">
                <div id="ficha-iconos"></div>
                <input type="hidden" id="link" value="<?=$this->project->link_rewrite?>"/>
                <input type="hidden" id="closed" value="<?=$this->closed?"1":""?>"/>
                <div id="votos">
                    <div>
                        <a id="down"><img src="/img/down.png"></a>
                        <span id="ldown">(<?=$this->votos['negativos']?>)</span>
                    </div>
                    <div>
                        <a id="up"><img src="/img/up.png"></a>
                        <span id="lup">(<?=$this->votos['positivos']?>)</span>
                    </div>
                </div>
                <h1><span>Proyecto: </span><?=$this->project->titulo?></h1>
                <div id="ficha-imagen"><img src="<?=$this->image?>"></div>
                <?if (strlen($this->project->video_embed)>10):?>
                    <div id="ficha-video"><?=$this->project->video_embed?></div>
                <?endif;?>
                <div id="ficha-info">
                    <div class="number"><span id="porcentaje"><?=round($this->porcentaje,0)?></span> %</div>
                    <div class="text">recaudado</div>
                    <div id="progressbar"></div>
                    <div class="text"><?=round($this->recaudado,0)?> de <?=round($this->project->importe_solicitado,0)?> &euro;</div>
                    <div class="number margin"><?=$this->numApoyos?></div>
                    <div class="text">apoyos</div>
                    <?if(!$this->closed):?>
                    <div class="number margin"><?=$this->days?></div>
                    <div class="text">días</div>
                    <?else:?>
                    <div class="number margin">Cerrado</div>
                    <div class="text">El plazo ha finalizado</div>
                    <?endif;?>
                </div>

                <div id="ficha-bottom">
                    <div id="project-social">
                        <a href="http://www.facebook.com/sharer.php?u=<?=$this->url?>&t=<?=$this->project->titulo?>" target="_blank"><img src="/img/fb_ico.png"/></a>
                        <a href="http://twitter.com/share?original_referer=<?=$this->url?>&source=tweetbutton&text=<?=$this->project->titulo?>" target="_blank" ><img src="/img/tw.png"/></a>
                        <a href="http://www.linkedin.com/cws/share?original_referer=<?=$this->url?>&url=<?=$this->url?>" target="_blank"><img src="/img/in.png"/></a>
                        <a href="http://www.tuenti.com/share?url=<?=$this->url?>" target="_blank"><img src="/img/tu.png"/></a>
                        
                    </div>
                    <h2>Descripci&oacute;n del Proyecto</h2>
                    <span id="descripcion"><?=nl2br($this->project->descripcion)?></span>
                </div>
            </div>
	</div>
	<div id="tabs-2">
            <div id="colaboradores">
                <?foreach($this->collaborators as $collaborator):?>
                    <div class="colaborador">
                        <h2><?=$collaborator['colaborador']?></h2>
                        <p class="contacto"><?=$collaborator['contacto']?></p>
                        <p><?=$collaborator['descripcion']?></p>
                    </div>
                <?endforeach;?>
                
            </div>
	</div>
	<div id="tabs-3">
            <div id="concurso">
                <h2><?=$this->project->titulo_concurso?></h2>
		<p><?=nl2br($this->project->descripcion_concurso)?></p>


                <?foreach($this->proposals as $proposal):?>
                    <div class="propuesta">
                        <div id="votos">
                            <div>
                                <a id="down-<?=$proposal['id_propuesta']?>" class="down"><img src="/img/down.png"></a>
                                <span id="ldown-<?=$proposal['id_propuesta']?>">(<?=$proposal['votes']['negativos']?>)</span>
                            </div>
                            <div>
                                <a id="up-<?=$proposal['id_propuesta']?>"" class="up"><img src="/img/up.png"></a>
                                <span id="lup-<?=$proposal['id_propuesta']?>">(<?=$proposal['votes']['positivos']?>)</span>
                            </div>
                        </div>
                        <h3>Propuesta de <?=$proposal['username']?></h3>

                            <p><?=nl2br($proposal['propuesta'])?></p>
                            <?if($proposal['adjunto']!=""):?>
                            <a href="/admin/<?=$proposal['adjunto']?>" target="_blank">Ver adjunto</a>
                            <?endif;?>
                        <img src="<?=$helper->image($proposal['id_usuario'], $proposal['imagen'])?>">
                        <div class="fecha"><?=$helperDate->Date2DateComment($proposal['fecha'])?></div>
                        <div>
                            <a class="show_comments" id="<?=$proposal['id_propuesta']?>"><?=(count($proposal['comments'])==0)?"Comentar":"Mostrar comentarios(".count($proposal['comments']).")"?></a>
                            </div>
                        <div id="comentarios_concurso_<?=$proposal['id_propuesta']?>" class="comentarios-concurso">

                            <div id="comentarios_<?=$proposal['id_propuesta']?>">
                                <?if(is_array($proposal['comments'])):
                                        foreach($proposal['comments'] as $comment):?>
                                    <div class="comentario-concurso">
                                        <img src="<?=$helper->image($comment['id_usuario'], $comment['imagen'])?>">
                                        <div>
                                            <span><?=$comment['username']?></span>
                                            <?=$comment['comentario']?>
                                        </div>
                                        <div class="fecha"><?=$helperDate->Date2DateComment($comment['fecha'])?></div>
                                    </div>
                                <?endforeach;
                                        endif;?>
                            </div>
                            <div id="entrada" >
                                <div><textarea name="txt-comentario-<?=$proposal['id_propuesta']?>" id="txt-comentario-<?=$proposal['id_propuesta']?>"  cols="40" rows="1"></textarea></div>
                                <div><input type="button" id="<?=$proposal['id_propuesta']?>" class="add-comentario btn-red" value="Comentar"/></div>
                            </div>
                        </div>
                    </div>
                <?endforeach;?>
                <div id="proponer"><input type="button" id="add-propuesta" class="btn-red" value="Proponer"/></div>
                
            </div>
	</div>
    </div>
    <div id="recompensas">
        <input type="hidden" id="id-recompensa"/>
        <input type="hidden" id="apoyo-minimo"/>
        <span>Recompensas por apoyar el proyecto</span>
        <ul class="scroll-content-item ui-widget-header">
            <?foreach($this->rewards as $reward):?>
            <li>
                <div class="recompensa-valor"><?=$reward->apoyo_minimo?>&euro;</div>
                <div class="recompensa-desc"><?=$reward->recompensa?></div>
                <div id="<?=$reward->id_recompensa."_".$reward->apoyo_minimo?>" class="btn-red">Apoyar</div>
            </li>
            <?endforeach;?>
            
        </ul>
        <?if(count($this->rewardsSale)>0):?>
            <span>Recompensas limitadas</span>
            <p>Solo se tendrá en cuenta el apoyo más alto</p>
            <ul class="scroll-content-item ui-widget-header">
                <?foreach($this->rewardsSale as $reward):?>
                <li>
                    <div class="recompensa-valor"><?=$reward->apoyo_minimo?>&euro;</div>
                    <div class="recompensa-desc"><?=$reward->recompensa?></div>
                    <div id="<?=$reward->id_recompensa."_".$reward->apoyo_minimo?>" class="btn-red">Apoyar</div>
                </li>
                <?endforeach;?>

            </ul>
        <?endif;?>
    </div>
    <div class="cl"></div>
    <div id="comentarios">
        <?foreach($this->comments as $comentario):?>
            <div class="comentario">
                <img src="<?=$helper->image($comentario['id_usuario'], $comentario['imagen'])?>">
                <div>
                    <span><?=$comentario['username']?></span>
                    <?=$comentario['comentario']?>
                </div>
                <div class="fecha">
                    <?=$helperDate->Date2DateComment($comentario['fecha'])?>
                </div>
            </div>
        <?endforeach?>
    </div>
    <div id="entrada" >
        <div><textarea name="comentario" id="txt-comentario" cols="80" rows="2"></textarea></div>
        <div><input type="button" id="add-comentario" class="btn-red" value="Comentar"/></div>
    </div>
    <div class="cl"></div>
</div>
<div id="dialog-form" title="Apoyar el proyecto">
    <div>
	<p class="validateTips"></p>

	<form>
	<fieldset>
		<label for="amount">Cantidad con la que apoyar</label>
		<input type="text" name="amount" id="amount" class="text ui-widget-content ui-corner-all" />
	</fieldset>
	</form>
    </div>
</div>

<div id="dialog-form-proposal" title="Realiza tu propuesta">
    <div>
	<p class="validateTips"></p>

        <form id="do-proposal" enctype="multipart/form-data"  method="post">
	<fieldset>
		<label for="proposal">Describe tu propuesta</label><br/>
		<textarea name="proposal" id="proposal" class="text ui-widget-content ui-corner-all"></textarea><br/>
                <label for="attached">Adjunto(si es necesario)</label><br/>
		<input type="file" name="attached" id="attached" class="text ui-widget-content ui-corner-all" />
	</fieldset>
	</form>
    </div>
</div>