<div id="panel-list">
    <div id="category-list">
        <span>Categories</span>
        <div class="mnu-cat"><a class="<?=(0==$this->idCategory?"active":"")?>" href="/proyectos/<?=$this->page?>">All</a></div>
        <?foreach ($this->categories as $category):?>
            <div class="mnu-cat"><a class="<?=($category['id_categoria']==$this->idCategory?"active":"")?>" href="/proyectos/<?=$this->page?>/<?=$category['id_categoria']?>"><?=$category['categoria']?></a></div>
        <?endforeach;?>
    </div>

    <?$i=0;
        foreach ($this->projects as $project):
          $i++?>
        <div class="item">
            <!--<div class="iconos"></div>-->
            <div class="title">Event:<br/><span><a href="/proyecto/<?=$project['link_rewrite']?>"><?=$project['titulo']?></a></span></div>
            <div class="project-image">
                <img width="123"  src="<?="/admin/".str_replace("/".$project['id_proyecto']."/", "/".$project['id_proyecto']."/160x/thumb_", $project['imagen']);?>">
            </div>
            <div class="project-info">
                    <div class="number"><span id="porcentaje_<?=$i?>"><?=round($project['porcentaje'],0)?></span> %</div>
                    <div class="text">Raised</div>
                    <div id="progressbar_<?=$i?>"></div>
                    <div class="number"><?=round($project['recaudado'],0)?> de <?=round($project['importe_solicitado'],0)?> &euro;</div>
                    <div class="number margin"><?=$project['numApoyos']?> <span class="text">supports</span></div>
                    <div class="number margin"><?=$project['days']?> <span class="text">days</span></div>

            </div>
            <div class="project-bottom">
                <?=$project['breve_descripcion']?>
            </div>

        </div>
    <?endforeach;?>
    <?if($i==0):?>
        <div class="msg">Sorry, at the moment we have no events here. Create yours!</div>
    <?endif;?>
   
    <div class="cl"></div>
     <?=$this->paginationControl($this->projects,'Sliding','project/list/pagination.phtml');?>
    <div class="cl"></div>

</div>