<div id="panel-list">
    <?$i=0;
        foreach ($this->projects as $project):
          $i++?>
        <div class="item">
            <div class="iconos"></div>
            <div class="title">Proyecto:<br/><span><a href="/proyecto/<?=$project['link_rewrite']?>"><?=$project['titulo']?></a></span></div>
            <div class="project-image">
                <img  src="<?="/admin/".str_replace("/".$project['id_proyecto']."/", "/".$project['id_proyecto']."/160x/thumb_", $project['imagen']);?>">
            </div>
            <div class="project-info">
                    <div class="number"><span id="porcentaje_<?=$i?>">0</span> %</div>
                    <div class="text">recaudado</div>
                    <div id="progressbar_<?=$i?>"></div>
                    <div class="number"><?=round($project['recaudado'],0)?> de <?=round($project['importe_solicitado'],0)?> &euro;</div>
                    <div class="number margin"><?=$project['numApoyos']?> <span class="text">apoyos</span></div>
                    <div class="number margin"><?=$project['days']?> <span class="text">dias</span></div>

            </div>
            <div class="project-bottom">
                <?=$project['breve_descripcion']?>
            </div>

        </div>
    <?endforeach;?>
   
    <div class="cl"></div>
     <?=$this->paginationControl($this->projects,'Sliding','project/list/pagination.phtml');?>
    <div class="cl"></div>

</div>